### ISSUE TITLE
Evol : Filtres appliqués - Afficher des étoiles plutôt que du texte

### ISSUE THREAD

**Issue by garensmile** [Smile-SA/magento2-module-elasticsuite-rating#1]
Je filtre par note 2/5, j'arrive sur cette page http://elasticsuite-for-retailer-demo.clients.smile.fr/women/tops-women.html?p=1&product_list_dir=desc&product_list_order=rating_summary&rating_summary=40

S'affiche dans le rappel des filtres : Product Rating 2 / 5 and more.

Ça serait plus sympa d'avoir les étoiles (comme sur le filtre)
![screenshot - 08092017 - 14 41 06](https://user-images.githubusercontent.com/29067543/30212111-c2b6aefc-94a3-11e7-9e29-3fc51b6a8f4a.png)

**Comment by afoucret** [comment]
All ElasticSuite filters are using text in the state area. (see color swatches or size as a good example) and in a standard Magento.
We have no plan for changing that.

But you can still do it by your own in your theme / project.

PS : next time try to submit your issue in english since we have user from everywhere in the world.
